### ISSUE TITLE
npm install  platon-truffle failed

### ISSUE THREAD

**Issue by hikelee** [PlatONnetwork/platon-truffle#23]
$cat /etc/lsb-release
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=18.04
DISTRIB_CODENAME=bionic
DISTRIB_DESCRIPTION="Ubuntu 18.04.3 LTS"
hike@u:/code/blockchain/HelloWorld/migrations$ lsb_relase

$npm -v
6.14.8
$node -v
v14.15.1

$$ npm install -g platon-truffle@0.13.1
npm WARN deprecated mkdirp@0.5.1: Legacy versions of mkdirp are no longer supported. Please update to mkdirp 1.x. (Note that the API surface has changed to use Promises in 1.x.)
/usr/local/node/14.15.1/bin/platon-truffle -> /usr/local/node/14.15.1/lib/node_modules/platon-truffle/build/cli.bundled.js

> platon-truffle@0.13.1 postinstall /usr/local/node/14.15.1/lib/node_modules/platon-truffle
> node ./scripts/postinstall.js

- Fetching solc version list from solc-bin. Attempt #1
- Downloading compiler. Attempt #1
Error: Error while attempting to download and cache solc 0.5.12: Command failed: node ./build/cli.bundled.js obtain --solc=0.5.12
- Fetching solc version list from solc-bin. Attempt #1
- Downloading compiler. Attempt #1

    at postinstallObtain (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/scripts/postinstall.js:13:11)
    at Object.<anonymous> (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/scripts/postinstall.js:20:3)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47
+ platon-truffle@0.13.1

**Comment by biganxin** [comment]
@fksyuan @xuwen
Please confirm these questions and add the corresponding labels. Thanks

**Comment by dugusanfeng** [comment]
这个只是缓存默认的编译器失败了，其实是安装下载安装好了的，你可以检查/usr/local/node/14.15.1/bin/platon-truffle是否存在，如果是linux系统的话，执行sudo ln -s /usr/local/node/14.15.1/bin/platon-truffle /usr/bin/platon-truffle,然后运行platon-truffle -v命令检查是否成功
