### ISSUE TITLE
platon-truffle init error

### ISSUE THREAD

**Issue by hikelee** [PlatONnetwork/platon-truffle#24]
platon-truffle init

✔ Preparing to download
✖ Downloading
RequestError: Error: self signed certificate
    at new RequestError (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/build/webpack:/node_modules/request-promise-core/lib/errors.js:14:1)
    at Request.plumbing.callback (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:87:1)
    at Request.RP$callback [as _callback] (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/build/webpack:/node_modules/request-promise-core/lib/plumbing.js:46:1)
    at self.callback (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/build/webpack:/node_modules/request/request.js:185:1)
    at Request.emit (events.js:315:20)
    at Request.onRequestError (/usr/local/node/14.15.1/lib/node_modules/platon-truffle/build/webpack:/node_modules/request/request.js:881:1)
    at ClientRequest.emit (events.js:315:20)
    at TLSSocket.socketErrorListener (_http_client.js:469:9)
    at TLSSocket.emit (events.js:315:20)
    at emitErrorNT (internal/streams/destroy.js:106:8)
    at emitErrorCloseNT (internal/streams/destroy.js:74:3)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
Truffle v0.13.0 (core: 0.13.0)
Node v14.15.1

**Comment by biganxin** [comment]
@fksyuan @xuwen
Please confirm these questions and add the corresponding labels. Thanks

**Comment by dugusanfeng** [comment]
这个问题可能需要检查你本地的网络问题，因为init命令会去连接github去clone一个模版项目下来，项目的地址是https://github.com/PlatONnetwork/truffle-box_bare-box
