### ISSUE TITLE
platon-truffle Compile  HelloWorld  failure

### ISSUE THREAD

**Issue by luoyele** [PlatONnetwork/platon-truffle#29]
platon-truffle Compile  HelloWorld  failure
HelloWorld   数据及操作详见  [https://devdocs.platon.network/docs/en/Wasm_Dev_Manual](url)

Compiling your contracts...
===========================
⠴ Downloading compiler. Attempt #1Error: Pull platon-cdt compiler failed: StatusCodeError: 404 - {"type":"Buffer","data":[78,111,116,32,70,111,117,110,100]}
    at /usr/local/node-v10.12.0-linux-x64/lib/node_modules/platon-truffle/build/webpack:/packages/compile-wasm/compilerSupplier/loadingStrategies/Remote.js:21:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Pull failed, try again

**Comment by biganxin** [comment]
@fksyuan  @xuwen
Please confirm these questions and add the corresponding labels. Thanks

**Comment by dugusanfeng** [comment]
这个错误我看了下文档，文档里的wasm版本号错误导致无法获取到正确的wasm编译器链接，如果是最新版本的platon-truffle，建议将truffle-config.js中的wasm的配置修改成v0.13.0

**Comment by biganxin** [comment]
@dugusanfeng 文档是否已修改，用户常遇到的问题最好补充到文档上，谢谢
